org: allenwalkerd3
app: wallet-tracker-service
service: wallet-tracker-service

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.app
    pythonBin: python3

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
